ERROR:app:Exception on /addjob [POST]
Traceback (most recent call last):
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 54, in addjob
    status = add_job(job_id, name, fdate)
  File "/home/a_bhatnagar/projects/date_filter_flask/db.py", line 50, in add_job
    status = db.jobs.insert_one({'job_id': jobid, 'user_name': name, 'time': date})
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: jobtest.jobs index: job_id_1 dup key: { job_id: 1 }
ERROR:app:Exception on /addjob [POST]
Traceback (most recent call last):
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 54, in addjob
    status = add_job(job_id, name, fdate)
  File "/home/a_bhatnagar/projects/date_filter_flask/db.py", line 50, in add_job
    status = db.jobs.insert_one({'job_id': jobid, 'user_name': name, 'time': date})
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/collection.py", line 597, in _insert_command
    _check_write_command_response(result)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/pymongo/helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: jobtest.jobs index: job_id_1 dup key: { job_id: 1 }
ERROR:app:Exception on /jobsreport [POST]
Traceback (most recent call last):
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 29, in jobsreport
    fdate = datetime.strptime(from_date, '%Y-%m-%d')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
ERROR:app:Exception on /daywisejobs [POST]
Traceback (most recent call last):
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a_bhatnagar/projects/date_filter_flask/.env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 41, in daywisejobs
    date = datetime.strptime(day, '%Y-%m-%d')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
